import type { ShiftStatus, Region } from "./shifts-data";

export interface ShiftTemplate {
  templateId: string;
  codePrefix: string;
  name: string;
  customer: string;
  customerId: string;
  region: Region;
  site: string;
  address: string;
  /** Day-of-week offset (0=Mon … 6=Sun). Array = repeats. */
  dayOffsets: number[];
  startHour: number;
  endHour: number;
  /** End time wraps past midnight (e.g. 22→06). */
  overnight?: boolean;
  required: number;
  /** 0..1 ratio of assigned/required. */
  fillRatio: number;
  status: ShiftStatus;
  payRateVnd: number;
  payRateUnit: "giờ" | "ca";
  payRateNote: string;
  requirements: string[];
  notes: string;
  /** Sample assignment names (cycled when generating). */
  sampleWorkers: Array<{ name: string; role: string }>;
}

export const SHIFT_TEMPLATES: ShiftTemplate[] = [
  // ── GHN Sorting (TP. HCM) ────────────────────────────────────────────
  {
    templateId: "ghn-vincom-weekend-sales",
    codePrefix: "GHN",
    name: "Ca bán hàng cuối tuần",
    customer: "GHN Sorting",
    customerId: "ghn-sorting",
    region: "TP. HCM",
    site: "Vincom Đồng Khởi",
    address: "72 Lê Thánh Tôn, Quận 1, TP. HCM",
    dayOffsets: [5, 6],
    startHour: 8,
    endHour: 17,
    required: 18,
    fillRatio: 0.78,
    status: "open",
    payRateVnd: 55_000,
    payRateUnit: "giờ",
    payRateNote: "Phụ cấp ăn ca ₫45.000",
    requirements: [
      "CTV có chứng nhận xác thực CCCD",
      "Có kinh nghiệm bán hàng retail",
      "Đồng phục theo brand cung cấp",
    ],
    notes: "Cần thêm worker để fill tối thiểu 18 ca.",
    sampleWorkers: [
      { name: "Nguyễn Văn An", role: "Trưởng nhóm" },
      { name: "Phạm Thu Dung", role: "Bán hàng" },
      { name: "Lê Minh Quân", role: "Bán hàng" },
    ],
  },
  {
    templateId: "ghn-gigamall-sampling",
    codePrefix: "GHN",
    name: "Ca activation sampling",
    customer: "GHN Sorting",
    customerId: "ghn-sorting",
    region: "TP. HCM",
    site: "Gigamall Thủ Đức",
    address: "240-242 Phạm Văn Đồng, TP. Thủ Đức",
    dayOffsets: [6],
    startHour: 10,
    endHour: 18,
    required: 8,
    fillRatio: 0.62,
    status: "critical",
    payRateVnd: 60_000,
    payRateUnit: "giờ",
    payRateNote: "Phụ cấp đi lại ₫50.000",
    requirements: [
      "Ngoại hình ưa nhìn",
      "Có kinh nghiệm sampling",
      "Sẵn sàng làm chủ nhật",
    ],
    notes: "Khu vực TTTM đông cuối tuần, ưu tiên worker chủ động.",
    sampleWorkers: [
      { name: "Trần Thị Bích", role: "Hostess" },
      { name: "Nguyễn Hà My", role: "Hostess" },
    ],
  },
  {
    templateId: "ghn-q7-sorting-morning",
    codePrefix: "GHN",
    name: "Ca phân loại hàng sáng",
    customer: "GHN Sorting",
    customerId: "ghn-sorting",
    region: "TP. HCM",
    site: "Trung tâm phân loại Quận 7",
    address: "KCN Tân Thuận, Quận 7, TP. HCM",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 6,
    endHour: 14,
    required: 25,
    fillRatio: 0.92,
    status: "filling",
    payRateVnd: 50_000,
    payRateUnit: "giờ",
    payRateNote: "Bữa sáng miễn phí",
    requirements: ["Sức khỏe tốt", "Có giấy khám sức khỏe trong 6 tháng"],
    notes: "Ca cố định, ưu tiên worker đi làm đều.",
    sampleWorkers: [
      { name: "Đỗ Hoàng Long", role: "Phân loại" },
      { name: "Nguyễn Văn Tài", role: "Phân loại" },
      { name: "Trần Đức Huy", role: "Trưởng ca" },
    ],
  },
  {
    templateId: "ghn-q7-sorting-afternoon",
    codePrefix: "GHN",
    name: "Ca phân loại hàng chiều",
    customer: "GHN Sorting",
    customerId: "ghn-sorting",
    region: "TP. HCM",
    site: "Trung tâm phân loại Quận 7",
    address: "KCN Tân Thuận, Quận 7, TP. HCM",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 14,
    endHour: 22,
    required: 22,
    fillRatio: 1.0,
    status: "full",
    payRateVnd: 52_000,
    payRateUnit: "giờ",
    payRateNote: "Phụ cấp ca chiều ₫30.000",
    requirements: ["Sức khỏe tốt"],
    notes: "Ca đã đủ người.",
    sampleWorkers: [
      { name: "Phan Quốc Việt", role: "Phân loại" },
      { name: "Lý Hoàng Nam", role: "Phân loại" },
    ],
  },
  {
    templateId: "ghn-q12-night",
    codePrefix: "GHN",
    name: "Ca xử lý hàng đêm",
    customer: "GHN Sorting",
    customerId: "ghn-sorting",
    region: "TP. HCM",
    site: "Kho GHN Quận 12",
    address: "Hà Huy Giáp, Quận 12, TP. HCM",
    dayOffsets: [0, 1, 2, 3, 4, 5],
    startHour: 22,
    endHour: 6,
    overnight: true,
    required: 15,
    fillRatio: 0.4,
    status: "critical",
    payRateVnd: 75_000,
    payRateUnit: "giờ",
    payRateNote: "Phụ cấp ca đêm ₫150.000",
    requirements: [
      "Sức khỏe đảm bảo cho ca đêm",
      "Mang đồng phục bảo hộ",
    ],
    notes: "Thiếu nghiêm trọng. Cần escalate sang đội tuyển dụng.",
    sampleWorkers: [
      { name: "Lê Hoàng Cường", role: "Vận hành kho" },
      { name: "Nguyễn Đình Phú", role: "Vận hành kho" },
    ],
  },

  // ── Ninja Van (Bình Dương / TP. HCM) ─────────────────────────────────
  {
    templateId: "ninja-vsip-night",
    codePrefix: "NJV",
    name: "Ca kho đêm A",
    customer: "Ninja Van",
    customerId: "ninja-van",
    region: "Bình Dương",
    site: "Kho Ninja Van DC1",
    address: "Lô C12 KCN VSIP1, Thuận An, Bình Dương",
    dayOffsets: [4, 5, 6],
    startHour: 22,
    endHour: 6,
    overnight: true,
    required: 15,
    fillRatio: 0.73,
    status: "critical",
    payRateVnd: 70_000,
    payRateUnit: "giờ",
    payRateNote: "Phụ cấp ca đêm ₫120.000",
    requirements: [
      "Chứng nhận an toàn lao động",
      "Sức khỏe đảm bảo cho ca đêm",
      "Mang đồng phục bảo hộ riêng",
    ],
    notes: "Cần điều phối viên có mặt trước 21:30.",
    sampleWorkers: [
      { name: "Lê Hoàng Cường", role: "Vận hành kho" },
      { name: "Trần Minh Thắng", role: "Vận hành kho" },
    ],
  },
  {
    templateId: "ninja-binhtan-day",
    codePrefix: "NJV",
    name: "Ca chia hàng ngày",
    customer: "Ninja Van",
    customerId: "ninja-van",
    region: "TP. HCM",
    site: "Kho Ninja Van Bình Tân",
    address: "KCN Tân Bình, Quận Bình Tân, TP. HCM",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 7,
    endHour: 15,
    required: 12,
    fillRatio: 0.83,
    status: "open",
    payRateVnd: 55_000,
    payRateUnit: "giờ",
    payRateNote: "Có cơm trưa miễn phí",
    requirements: ["Sức khỏe tốt"],
    notes: "",
    sampleWorkers: [
      { name: "Phạm Văn Đức", role: "Chia hàng" },
      { name: "Nguyễn Thị Lan", role: "Chia hàng" },
    ],
  },
  {
    templateId: "ninja-thuduc-afternoon",
    codePrefix: "NJV",
    name: "Ca giao hàng chiều",
    customer: "Ninja Van",
    customerId: "ninja-van",
    region: "TP. HCM",
    site: "Hub Ninja Van Thủ Đức",
    address: "Đường Lê Văn Việt, TP. Thủ Đức",
    dayOffsets: [0, 1, 2, 3, 4, 5],
    startHour: 13,
    endHour: 20,
    required: 18,
    fillRatio: 1.0,
    status: "full",
    payRateVnd: 60_000,
    payRateUnit: "giờ",
    payRateNote: "Phụ cấp xăng xe ₫80.000/ca",
    requirements: ["Có xe máy", "Bằng lái A1", "Smartphone"],
    notes: "Đã đủ người, theo dõi tỉ lệ on-time.",
    sampleWorkers: [
      { name: "Bùi Quốc Anh", role: "Shipper" },
      { name: "Lê Văn Hùng", role: "Shipper" },
    ],
  },

  // ── Shopee Express (Hà Nội + Đà Nẵng) ────────────────────────────────
  {
    templateId: "shopee-caugiay-recep",
    codePrefix: "SPX",
    name: "Ca lễ tân chiều",
    customer: "Shopee Express Official",
    customerId: "shopee-express",
    region: "Hà Nội",
    site: "Văn phòng Cầu Giấy",
    address: "12 Trần Thái Tông, Cầu Giấy, Hà Nội",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 13,
    endHour: 18,
    required: 6,
    fillRatio: 1.0,
    status: "full",
    payRateVnd: 65_000,
    payRateUnit: "giờ",
    payRateNote: "Bao gồm phụ cấp đồng phục",
    requirements: [
      "Giao tiếp tốt, biết tiếng Anh cơ bản",
      "Đã hoàn tất xác thực",
      "Đồng phục lễ tân do clinic cung cấp",
    ],
    notes: "Ca đã đủ người, theo dõi check-in đúng giờ.",
    sampleWorkers: [
      { name: "Trần Thị Bích", role: "Lễ tân" },
      { name: "Lê Mai Anh", role: "Lễ tân" },
    ],
  },
  {
    templateId: "shopee-longbien-sorting",
    codePrefix: "SPX",
    name: "Ca phân loại Long Biên",
    customer: "Shopee Express Official",
    customerId: "shopee-express",
    region: "Hà Nội",
    site: "Hub Long Biên",
    address: "KCN Sài Đồng, Long Biên, Hà Nội",
    dayOffsets: [0, 1, 2, 3, 4, 5],
    startHour: 6,
    endHour: 14,
    required: 30,
    fillRatio: 0.87,
    status: "filling",
    payRateVnd: 52_000,
    payRateUnit: "giờ",
    payRateNote: "Cơm sáng + trưa miễn phí",
    requirements: ["Sức khỏe tốt"],
    notes: "Cần fill thêm 4 worker.",
    sampleWorkers: [
      { name: "Đỗ Mạnh Hùng", role: "Phân loại" },
      { name: "Nguyễn Bích Ngọc", role: "Phân loại" },
    ],
  },
  {
    templateId: "shopee-danang-recep",
    codePrefix: "SPX",
    name: "Ca CSKH Đà Nẵng",
    customer: "Shopee Express Official",
    customerId: "shopee-express",
    region: "Đà Nẵng",
    site: "Văn phòng Hải Châu",
    address: "Bạch Đằng, Hải Châu, Đà Nẵng",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 8,
    endHour: 17,
    required: 10,
    fillRatio: 0.7,
    status: "open",
    payRateVnd: 58_000,
    payRateUnit: "giờ",
    payRateNote: "",
    requirements: ["Giao tiếp tốt", "Tin học văn phòng"],
    notes: "",
    sampleWorkers: [
      { name: "Nguyễn Văn Toàn", role: "CSKH" },
      { name: "Phạm Thị Hồng", role: "CSKH" },
    ],
  },

  // ── Highlands Coffee (TP. HCM + Hà Nội) ─────────────────────────────
  {
    templateId: "highlands-bitexco-morning",
    codePrefix: "HLC",
    name: "Ca pha chế sáng",
    customer: "Highlands Coffee",
    customerId: "highlands-coffee",
    region: "TP. HCM",
    site: "Highlands Bitexco",
    address: "Tầng B2 Bitexco, Quận 1, TP. HCM",
    dayOffsets: [0, 1, 2, 3, 4, 5, 6],
    startHour: 6,
    endHour: 14,
    required: 4,
    fillRatio: 1.0,
    status: "full",
    payRateVnd: 45_000,
    payRateUnit: "giờ",
    payRateNote: "Có ăn nhẹ",
    requirements: ["Đã qua training barista cơ bản"],
    notes: "",
    sampleWorkers: [
      { name: "Lê Thanh Bình", role: "Barista" },
      { name: "Trần Minh Tâm", role: "Barista" },
    ],
  },
  {
    templateId: "highlands-bitexco-evening",
    codePrefix: "HLC",
    name: "Ca phục vụ tối",
    customer: "Highlands Coffee",
    customerId: "highlands-coffee",
    region: "TP. HCM",
    site: "Highlands Bitexco",
    address: "Tầng B2 Bitexco, Quận 1, TP. HCM",
    dayOffsets: [0, 1, 2, 3, 4, 5, 6],
    startHour: 14,
    endHour: 22,
    required: 6,
    fillRatio: 0.66,
    status: "open",
    payRateVnd: 50_000,
    payRateUnit: "giờ",
    payRateNote: "Phụ cấp ca tối ₫30.000",
    requirements: [],
    notes: "",
    sampleWorkers: [
      { name: "Nguyễn Hữu Phước", role: "Phục vụ" },
      { name: "Đoàn Mỹ Linh", role: "Phục vụ" },
    ],
  },
  {
    templateId: "highlands-hoankiem",
    codePrefix: "HLC",
    name: "Ca pha chế Hoàn Kiếm",
    customer: "Highlands Coffee",
    customerId: "highlands-coffee",
    region: "Hà Nội",
    site: "Highlands Bờ Hồ",
    address: "Lê Thái Tổ, Hoàn Kiếm, Hà Nội",
    dayOffsets: [0, 1, 2, 3, 4, 5, 6],
    startHour: 7,
    endHour: 15,
    required: 5,
    fillRatio: 0.8,
    status: "open",
    payRateVnd: 47_000,
    payRateUnit: "giờ",
    payRateNote: "",
    requirements: ["Đã qua training barista"],
    notes: "",
    sampleWorkers: [
      { name: "Vũ Minh Đức", role: "Barista" },
      { name: "Nguyễn Hồng Hạnh", role: "Barista" },
    ],
  },

  // ── Lazada (Bình Dương + Hà Nội) ─────────────────────────────────────
  {
    templateId: "lazada-vsip2-day",
    codePrefix: "LZD",
    name: "Ca xếp hàng kho VSIP2",
    customer: "Lazada Logistics",
    customerId: "lazada-logistics",
    region: "Bình Dương",
    site: "Kho Lazada VSIP2",
    address: "VSIP2, Tân Uyên, Bình Dương",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 8,
    endHour: 17,
    required: 35,
    fillRatio: 0.85,
    status: "filling",
    payRateVnd: 54_000,
    payRateUnit: "giờ",
    payRateNote: "Bao xe đưa đón từ Thủ Đức",
    requirements: ["Sức khỏe tốt", "Cao trên 1m60 ưu tiên"],
    notes: "Volume cao mùa sale, cần fill nhanh.",
    sampleWorkers: [
      { name: "Phạm Quang Hải", role: "Vận hành" },
      { name: "Nguyễn Mai Hoa", role: "Vận hành" },
    ],
  },
  {
    templateId: "lazada-vsip2-night",
    codePrefix: "LZD",
    name: "Ca xếp hàng kho VSIP2 đêm",
    customer: "Lazada Logistics",
    customerId: "lazada-logistics",
    region: "Bình Dương",
    site: "Kho Lazada VSIP2",
    address: "VSIP2, Tân Uyên, Bình Dương",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 22,
    endHour: 6,
    overnight: true,
    required: 20,
    fillRatio: 0.45,
    status: "critical",
    payRateVnd: 78_000,
    payRateUnit: "giờ",
    payRateNote: "Phụ cấp ca đêm ₫150.000 + xe đưa đón",
    requirements: ["Sức khỏe đảm bảo ca đêm", "Đồng phục bảo hộ"],
    notes: "Tỉ lệ thiếu cao nhất tháng.",
    sampleWorkers: [
      { name: "Lê Văn Sơn", role: "Vận hành" },
      { name: "Trần Quốc Bảo", role: "Vận hành" },
    ],
  },
  {
    templateId: "lazada-hanoi-day",
    codePrefix: "LZD",
    name: "Ca chia hàng Hà Nội",
    customer: "Lazada Logistics",
    customerId: "lazada-logistics",
    region: "Hà Nội",
    site: "Hub Lazada Hà Đông",
    address: "KCN Phú Lương, Hà Đông, Hà Nội",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 7,
    endHour: 15,
    required: 25,
    fillRatio: 0.92,
    status: "filling",
    payRateVnd: 53_000,
    payRateUnit: "giờ",
    payRateNote: "",
    requirements: ["Sức khỏe tốt"],
    notes: "",
    sampleWorkers: [
      { name: "Vũ Đình Khôi", role: "Chia hàng" },
      { name: "Đỗ Thanh Hằng", role: "Chia hàng" },
    ],
  },

  // ── Pizza 4P's (TP. HCM) ─────────────────────────────────────────────
  {
    templateId: "p4p-le-thanh-ton-evening",
    codePrefix: "P4P",
    name: "Ca phục vụ nhà hàng tối",
    customer: "Pizza 4P's",
    customerId: "pizza-4ps",
    region: "TP. HCM",
    site: "Pizza 4P's Lê Thánh Tôn",
    address: "8/15 Lê Thánh Tôn, Quận 1, TP. HCM",
    dayOffsets: [3, 4, 5, 6],
    startHour: 17,
    endHour: 23,
    required: 10,
    fillRatio: 0.7,
    status: "open",
    payRateVnd: 58_000,
    payRateUnit: "giờ",
    payRateNote: "Bao ăn ca + tip",
    requirements: ["Tiếng Anh giao tiếp", "Ngoại hình ưa nhìn"],
    notes: "Khách Tây cao, ưu tiên tiếng Anh.",
    sampleWorkers: [
      { name: "Nguyễn Thuỳ Linh", role: "Phục vụ" },
      { name: "Lê Hoàng Tú", role: "Phục vụ" },
    ],
  },
  {
    templateId: "p4p-saigoncenter-lunch",
    codePrefix: "P4P",
    name: "Ca phục vụ trưa",
    customer: "Pizza 4P's",
    customerId: "pizza-4ps",
    region: "TP. HCM",
    site: "Pizza 4P's Saigon Centre",
    address: "65 Lê Lợi, Quận 1, TP. HCM",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 10,
    endHour: 15,
    required: 8,
    fillRatio: 1.0,
    status: "full",
    payRateVnd: 55_000,
    payRateUnit: "giờ",
    payRateNote: "Bao cơm trưa",
    requirements: [],
    notes: "",
    sampleWorkers: [
      { name: "Phan Hoài Thu", role: "Phục vụ" },
      { name: "Trần Đăng Khoa", role: "Phục vụ" },
    ],
  },

  // ── CGV Cinema (multiple) ────────────────────────────────────────────
  {
    templateId: "cgv-vincom-weekend",
    codePrefix: "CGV",
    name: "Ca soát vé cuối tuần",
    customer: "CGV Cinemas",
    customerId: "cgv-cinemas",
    region: "TP. HCM",
    site: "CGV Vincom Đồng Khởi",
    address: "Tầng 3 Vincom Đồng Khởi, Q1, TP. HCM",
    dayOffsets: [5, 6],
    startHour: 12,
    endHour: 22,
    required: 12,
    fillRatio: 0.83,
    status: "filling",
    payRateVnd: 48_000,
    payRateUnit: "giờ",
    payRateNote: "Vé xem phim miễn phí",
    requirements: ["Giao tiếp tốt"],
    notes: "Cuối tuần đông, cần điều phối 30 phút trước giờ ca.",
    sampleWorkers: [
      { name: "Lý Bảo Châu", role: "Soát vé" },
      { name: "Hoàng Việt Anh", role: "Soát vé" },
    ],
  },
  {
    templateId: "cgv-vincom-weekday",
    codePrefix: "CGV",
    name: "Ca bán vé trong tuần",
    customer: "CGV Cinemas",
    customerId: "cgv-cinemas",
    region: "TP. HCM",
    site: "CGV Vincom Đồng Khởi",
    address: "Tầng 3 Vincom Đồng Khởi, Q1, TP. HCM",
    dayOffsets: [0, 1, 2, 3, 4],
    startHour: 12,
    endHour: 20,
    required: 6,
    fillRatio: 1.0,
    status: "full",
    payRateVnd: 46_000,
    payRateUnit: "giờ",
    payRateNote: "",
    requirements: [],
    notes: "",
    sampleWorkers: [
      { name: "Ngô Thanh Trúc", role: "Bán vé" },
      { name: "Đào Thị Mai", role: "Bán vé" },
    ],
  },
  {
    templateId: "cgv-vincom-haiphong",
    codePrefix: "CGV",
    name: "Ca soát vé Vincom Hải Phòng",
    customer: "CGV Cinemas",
    customerId: "cgv-cinemas",
    region: "Hải Phòng",
    site: "CGV Vincom Hải Phòng",
    address: "Vincom Plaza, Lê Hồng Phong, Hải Phòng",
    dayOffsets: [4, 5, 6],
    startHour: 13,
    endHour: 22,
    required: 8,
    fillRatio: 0.5,
    status: "critical",
    payRateVnd: 47_000,
    payRateUnit: "giờ",
    payRateNote: "",
    requirements: ["Giao tiếp tốt"],
    notes: "Thiếu nhân sự, cần tuyển thêm.",
    sampleWorkers: [
      { name: "Nguyễn Quang Vinh", role: "Soát vé" },
    ],
  },

  // ── J&T Express (Cần Thơ) ────────────────────────────────────────────
  {
    templateId: "jt-cantho-morning",
    codePrefix: "JNT",
    name: "Ca phân loại sáng",
    customer: "J&T Express",
    customerId: "jt-express",
    region: "Cần Thơ",
    site: "Kho J&T Cái Răng",
    address: "Quốc lộ 1A, Cái Răng, Cần Thơ",
    dayOffsets: [0, 1, 2, 3, 4, 5],
    startHour: 6,
    endHour: 14,
    required: 14,
    fillRatio: 0.93,
    status: "filling",
    payRateVnd: 48_000,
    payRateUnit: "giờ",
    payRateNote: "",
    requirements: ["Sức khỏe tốt"],
    notes: "",
    sampleWorkers: [
      { name: "Lê Văn Khang", role: "Phân loại" },
      { name: "Trần Thị Tuyết", role: "Phân loại" },
    ],
  },
];
