export interface AvatarUser {
  src: string;
  name: string;
  username: string;
}

export const AVATARS: AvatarUser[] = [
  { src: "/avatars/avatar-001.jpg", name: "Olivia Rhye", username: "olivia" },
  { src: "/avatars/avatar-002.jpg", name: "Phoenix Baker", username: "phoenix" },
  { src: "/avatars/avatar-003.jpg", name: "Lana Steiner", username: "lana" },
  { src: "/avatars/avatar-004.jpg", name: "Demi Wilkinson", username: "demi" },
  { src: "/avatars/avatar-005.jpg", name: "Candice Wu", username: "candice" },
  { src: "/avatars/avatar-006.jpg", name: "Natali Craig", username: "natali" },
  { src: "/avatars/avatar-007.jpg", name: "Drew Cano", username: "drew" },
  { src: "/avatars/avatar-008.jpg", name: "Orlando Diggs", username: "orlando" },
  { src: "/avatars/avatar-009.jpg", name: "Andi Lane", username: "andi" },
  { src: "/avatars/avatar-010.jpg", name: "Kate Morrison", username: "kate" },
  { src: "/avatars/avatar-011.jpg", name: "Koray Okumus", username: "koray" },
  { src: "/avatars/avatar-012.jpg", name: "Ava Wright", username: "ava" },
  { src: "/avatars/avatar-013.jpg", name: "Eve Leroy", username: "eve" },
  { src: "/avatars/avatar-014.jpg", name: "Zahir Mays", username: "zahir" },
  { src: "/avatars/avatar-015.jpg", name: "Joshua Wilson", username: "joshua" },
  { src: "/avatars/avatar-016.jpg", name: "Rene Wells", username: "rene" },
  { src: "/avatars/avatar-017.jpg", name: "Lori Bryson", username: "lori" },
  { src: "/avatars/avatar-018.jpg", name: "Analah Whitten", username: "analah" },
  { src: "/avatars/avatar-019.jpg", name: "Noah Pierre", username: "noah" },
  { src: "/avatars/avatar-020.jpg", name: "Katherine Moss", username: "katherine" },
  { src: "/avatars/avatar-021.jpg", name: "Mollie Hall", username: "mollie" },
  { src: "/avatars/avatar-022.jpg", name: "Eduard Franz", username: "eduard" },
  { src: "/avatars/avatar-023.jpg", name: "Alec Whitten", username: "alec" },
  { src: "/avatars/avatar-024.jpg", name: "Eva Bond", username: "eva" },
  { src: "/avatars/avatar-025.jpg", name: "Sophia Perez", username: "sophia" },
  { src: "/avatars/avatar-026.jpg", name: "Lyle Kauffman", username: "lyle" },
  { src: "/avatars/avatar-027.jpg", name: "Kelly Williams", username: "kelly" },
  { src: "/avatars/avatar-028.jpg", name: "Lucy Bond", username: "lucy" },
  { src: "/avatars/avatar-029.jpg", name: "Alisa Hester", username: "alisa" },
  { src: "/avatars/avatar-030.jpg", name: "Amanda Lowery", username: "amanda" },
  { src: "/avatars/avatar-031.jpg", name: "Amelie Bennett", username: "amelie" },
  { src: "/avatars/avatar-032.jpg", name: "Amelie Laurent", username: "amelie.l" },
  { src: "/avatars/avatar-033.jpg", name: "Ammar Foley", username: "ammar" },
  { src: "/avatars/avatar-034.jpg", name: "Anaiah Whitten", username: "anaiah" },
  { src: "/avatars/avatar-035.jpg", name: "Andi Lane", username: "andi.l" },
  { src: "/avatars/avatar-036.jpg", name: "Angelica Wallace", username: "angelica" },
  { src: "/avatars/avatar-037.jpg", name: "Anita Cruz", username: "anita" },
  { src: "/avatars/avatar-038.jpg", name: "Ashwin Santiago", username: "ashwin" },
  { src: "/avatars/avatar-039.jpg", name: "Aston Hood", username: "aston" },
  { src: "/avatars/avatar-040.jpg", name: "Ava Bentley", username: "ava.b" },
  { src: "/avatars/avatar-041.jpg", name: "Ayah Wilkinson", username: "ayah" },
  { src: "/avatars/avatar-042.jpg", name: "Aysha Becker", username: "aysha" },
  { src: "/avatars/avatar-043.jpg", name: "Alisha Hester", username: "alisha" },
  { src: "/avatars/avatar-044.jpg", name: "Rosasie Melvin", username: "rosasie" },
  { src: "/avatars/avatar-045.jpg", name: "Loki Bright", username: "loki" },
  { src: "/avatars/avatar-046.jpg", name: "Aliah Lane", username: "aliah" },
  { src: "/avatars/avatar-047.jpg", name: "Anita Cruz", username: "anita.c" },
  { src: "/avatars/avatar-048.jpg", name: "Kari Rasmussen", username: "kari" },
  { src: "/avatars/avatar-049.jpg", name: "Nala Doms", username: "nala" },
  { src: "/avatars/avatar-050.jpg", name: "Amelie Laurent", username: "amelie.lt" },
  { src: "/avatars/avatar-051.jpg", name: "Sienna Hewitt", username: "sienna" },
  { src: "/avatars/avatar-052.jpg", name: "Ammar Foley", username: "ammar.f" },
  { src: "/avatars/avatar-053.jpg", name: "Pippa Wilkinson", username: "pippa" },
  { src: "/avatars/avatar-054.jpg", name: "Ody Schroeder", username: "ody" },
  { src: "/avatars/avatar-055.jpg", name: "Mathilde Lewis", username: "mathilde" },
  { src: "/avatars/avatar-056.jpg", name: "Julius Vaughan", username: "julius" },
  { src: "/avatars/avatar-057.jpg", name: "Nguyen Thi Lan", username: "lan.nguyen" },
  { src: "/avatars/avatar-058.jpg", name: "Tran Van Minh", username: "minh.tran" },
  { src: "/avatars/avatar-059.jpg", name: "Pham Thi Hoa", username: "hoa.pham" },
  { src: "/avatars/avatar-060.jpg", name: "Le Van Duc", username: "duc.le" },
  { src: "/avatars/avatar-061.jpg", name: "Hoang Thi Mai", username: "mai.hoang" },
  { src: "/avatars/avatar-062.jpg", name: "Vo Thi Thu", username: "thu.vo" },
  { src: "/avatars/avatar-063.jpg", name: "Bui Van Thanh", username: "thanh.bui" },
  { src: "/avatars/avatar-064.jpg", name: "Dang Thi Ngoc", username: "ngoc.dang" },
  { src: "/avatars/avatar-065.jpg", name: "Do Van Khanh", username: "khanh.do" },
  { src: "/avatars/avatar-066.jpg", name: "Vu Thi Linh", username: "linh.vu" },
  { src: "/avatars/avatar-067.jpg", name: "Dinh Van Long", username: "long.dinh" },
  { src: "/avatars/avatar-068.jpg", name: "Ly Thi Hong", username: "hong.ly" },
  { src: "/avatars/avatar-069.jpg", name: "Phan Van An", username: "an.phan" },
  { src: "/avatars/avatar-070.jpg", name: "Trinh Thi Yen", username: "yen.trinh" },
  { src: "/avatars/avatar-071.jpg", name: "Ngo Van Tuan", username: "tuan.ngo" },
  { src: "/avatars/avatar-072.jpg", name: "Cao Thi Bich", username: "bich.cao" },
  { src: "/avatars/avatar-073.jpg", name: "Duong Van Nam", username: "nam.duong" },
  { src: "/avatars/avatar-074.jpg", name: "Mai Thi Thuy", username: "thuy.mai" },
  { src: "/avatars/avatar-075.jpg", name: "Luong Van Hai", username: "hai.luong" },
  { src: "/avatars/avatar-076.jpg", name: "Truong Thi Kim", username: "kim.truong" },
  { src: "/avatars/avatar-077.jpg", name: "Tong Van Phuc", username: "phuc.tong" },
  { src: "/avatars/avatar-078.jpg", name: "Ha Thi Tuyen", username: "tuyen.ha" },
  { src: "/avatars/avatar-079.jpg", name: "Lam Van Kiet", username: "kiet.lam" },
  { src: "/avatars/avatar-080.jpg", name: "Chau Thi Phuong", username: "phuong.chau" },
  { src: "/avatars/avatar-081.jpg", name: "Yuki Tanaka", username: "yuki" },
  { src: "/avatars/avatar-082.jpg", name: "Aiko Yamamoto", username: "aiko" },
  { src: "/avatars/avatar-083.jpg", name: "Haruto Suzuki", username: "haruto" },
  { src: "/avatars/avatar-084.jpg", name: "Min-jun Lee", username: "minjun" },
  { src: "/avatars/avatar-085.jpg", name: "Seo-yeon Park", username: "seoyeon" },
  { src: "/avatars/avatar-086.jpg", name: "Ji-woo Kim", username: "jiwoo" },
  { src: "/avatars/avatar-087.jpg", name: "Wei Chen", username: "wei" },
  { src: "/avatars/avatar-088.jpg", name: "Xiao Lin", username: "xiao" },
  { src: "/avatars/avatar-089.jpg", name: "Mei Zhang", username: "mei" },
  { src: "/avatars/avatar-090.jpg", name: "Priya Sharma", username: "priya" },
  { src: "/avatars/avatar-091.jpg", name: "Arjun Patel", username: "arjun" },
  { src: "/avatars/avatar-092.jpg", name: "Kavya Nair", username: "kavya" },
  { src: "/avatars/avatar-093.jpg", name: "Rohan Mehta", username: "rohan" },
  { src: "/avatars/avatar-094.jpg", name: "Ananya Singh", username: "ananya" },
  { src: "/avatars/avatar-095.jpg", name: "Isabelle Dupont", username: "isabelle" },
  { src: "/avatars/avatar-096.jpg", name: "Matteo Rossi", username: "matteo" },
  { src: "/avatars/avatar-097.jpg", name: "Sofia Garcia", username: "sofia" },
  { src: "/avatars/avatar-098.jpg", name: "Lucas Müller", username: "lucas" },
  { src: "/avatars/avatar-099.jpg", name: "Emma Johansson", username: "emma" },
  { src: "/avatars/avatar-100.jpg", name: "Liam O'Brien", username: "liam" },
  { src: "/avatars/avatar-101.jpg", name: "Amara Osei", username: "amara" },
  { src: "/avatars/avatar-102.jpg", name: "Kofi Mensah", username: "kofi" },
  { src: "/avatars/avatar-103.jpg", name: "Fatima Al-Hassan", username: "fatima" },
  { src: "/avatars/avatar-104.jpg", name: "Omar Sharif", username: "omar" },
  { src: "/avatars/avatar-105.jpg", name: "Laila Benali", username: "laila" },
  { src: "/avatars/avatar-106.jpg", name: "Carlos Rivera", username: "carlos" },
  { src: "/avatars/avatar-107.jpg", name: "Valentina Moreno", username: "valentina" },
  { src: "/avatars/avatar-108.jpg", name: "Diego Hernandez", username: "diego" },
  { src: "/avatars/avatar-109.jpg", name: "Camila Santos", username: "camila" },
  { src: "/avatars/avatar-110.jpg", name: "Rafael Costa", username: "rafael" },
  { src: "/avatars/avatar-111.jpg", name: "Zara Ahmed", username: "zara" },
  { src: "/avatars/avatar-112.jpg", name: "Tariq Hassan", username: "tariq" },
  { src: "/avatars/avatar-113.jpg", name: "Nadia Petrov", username: "nadia" },
  { src: "/avatars/avatar-114.jpg", name: "Ivan Volkov", username: "ivan" },
  { src: "/avatars/avatar-115.jpg", name: "Anika Weber", username: "anika" },
  { src: "/avatars/avatar-116.jpg", name: "Sven Larsson", username: "sven" },
  { src: "/avatars/avatar-117.jpg", name: "Freya Nielsen", username: "freya" },
  { src: "/avatars/avatar-118.jpg", name: "Mikael Lindqvist", username: "mikael" },
  { src: "/avatars/avatar-119.jpg", name: "Chioma Okafor", username: "chioma" },
  { src: "/avatars/avatar-120.jpg", name: "Emeka Nwosu", username: "emeka" },
  { src: "/avatars/avatar-121.jpg", name: "Zanele Dlamini", username: "zanele" },
  { src: "/avatars/avatar-122.jpg", name: "Thabo Molefe", username: "thabo" },
  { src: "/avatars/avatar-123.jpg", name: "Aroha Ngata", username: "aroha" },
  { src: "/avatars/avatar-124.jpg", name: "Tane Rawiri", username: "tane" },
  { src: "/avatars/avatar-125.jpg", name: "Hemi Walker", username: "hemi" },
  { src: "/avatars/avatar-126.png", name: "Wren Scott", username: "wren" },
];
