export interface CompanyLogo {
  slug: string;
  name: string;
  domain: string;
  logomark: string;
  full: string;
}

function logo(slug: string, name: string, domain: string): CompanyLogo {
  return {
    slug,
    name,
    domain,
    logomark: `/logos/logomark/${slug}.svg`,
    full: `/logos/full/${slug}.svg`,
  };
}

export const LOGOS: CompanyLogo[] = [
  logo("3portals", "3Portals", "3portals.io"),
  logo("45-degrees", "45 Degrees", "45-degrees.io"),
  logo("acme-corp", "Acme Corp", "acme-corp.io"),
  logo("alpha-wave", "AlphaWave", "alphawave.io"),
  logo("alt-shift", "Alt+Shift", "altshift.io"),
  logo("biosynthesis", "Biosynthesis", "biosynthesis.io"),
  logo("boltshift", "Boltshift", "boltshift.io"),
  logo("building-blocks", "Building Blocks", "buildingblocks.io"),
  logo("calescence", "Calescence", "calescence.io"),
  logo("capsule", "Capsule", "capsule.io"),
  logo("catalog", "Catalog", "catalog.io"),
  logo("chromatools", "Chromatools", "chromatools.io"),
  logo("clandestine", "Clandestine", "clandestine.io"),
  logo("cloud-watch", "CloudWatch", "cloudwatch.app"),
  logo("codecraft", "Codecraft", "codecraft.io"),
  logo("command-r", "Command R", "command-r.io"),
  logo("constellation", "Constellation", "constellation.io"),
  logo("contrast-ai", "ContrastAI", "contrastai.com"),
  logo("convergence", "Convergence", "convergence.io"),
  logo("cooperative", "Cooperative", "cooperative.io"),
  logo("core-os", "CoreOS", "coreos.io"),
  logo("cubekit", "Cubekit", "cubekit.io"),
  logo("easy-tax", "EasyTax", "easytax.io"),
  logo("eclipseful", "Eclipseful", "eclipseful.io"),
  logo("eightball", "Eightball", "eightball.io"),
  logo("elasticware", "Elasticware", "elasticware.io"),
  logo("enn-labs", "Enn Labs", "ennlabs.io"),
  logo("ephemeral", "Ephemeral", "ephemeral.io"),
  logo("epicurious", "Epicurious", "epicurious.io"),
  logo("euphoria", "Euphoria", "euphoria.io"),
  logo("europa", "Europa", "europa.io"),
  logo("feather-dev", "FeatherDev", "featherdev.io"),
  logo("flora-fauna", "Flora & Fauna", "florafauna.io"),
  logo("focal-point", "Focal Point", "focalpoint.io"),
  logo("foresight", "Foresight", "foresight.io"),
  logo("fourpoints", "Fourpoints", "fourpoints.io"),
  logo("frequencii", "Frequencii", "frequencii.io"),
  logo("galileo", "Galileo", "galileo.io"),
  logo("global-bank", "Global Bank", "globalbank.io"),
  logo("goodwell", "Goodwell", "goodwell.io"),
  logo("hexahedron", "Hexahedron", "hexahedron.io"),
  logo("hexsmith", "Hexsmith", "hexsmith.io"),
  logo("hourglass", "Hourglass", "hourglass.io"),
  logo("ikigai-labs", "Ikigai Labs", "ikigailabs.io"),
  logo("img-compress", "ImgCompress", "imgcompress.io"),
  logo("interlock", "Interlock", "interlock.io"),
  logo("kintsugi", "Kintsugi", "kintsugi.io"),
  logo("launch-simple", "LaunchSimple", "launchsimple.io"),
  logo("layers", "Layers", "layers.io"),
  logo("leapyear", "Leapyear", "leapyear.io"),
  logo("lightbox", "Lightbox", "lightbox.io"),
  logo("lightspeed", "Lightspeed", "lightspeed.io"),
  logo("luckycharm", "Luckycharm", "luckycharm.io"),
  logo("luminary", "Luminary", "luminary.io"),
  logo("luminescence", "Luminescence", "luminescence.io"),
  logo("luminous", "Luminous", "luminous.io"),
  logo("magnolia", "Magnolia", "magnolia.io"),
  logo("mastermail", "Mastermail", "mastermail.io"),
  logo("nietzsche", "Nietzsche", "nietzsche.io"),
  logo("norse-star", "Norse Star", "norsestar.io"),
  logo("odeao-labs", "Odeao Labs", "odeaolabs.io"),
  logo("ollio", "Ollio", "ollio.io"),
  logo("pagemanage", "Pagemanage", "pagemanage.io"),
  logo("peregrin", "Peregrin", "peregrin.io"),
  logo("pictel-ai", "PictelAI", "pictelai.io"),
  logo("pollinate", "Pollinate", "pollinate.io"),
  logo("polymath", "Polymath", "polymath.io"),
  logo("powersurge", "Powersurge", "powersurge.io"),
  logo("prometheus", "Prometheus", "prometheus.io"),
  logo("quantum", "Quantum", "quantum.io"),
  logo("quartz-ai", "QuartzAI", "quartzai.io"),
  logo("quixotic", "Quixotic", "quixotic.io"),
  logo("quotient", "Quotient", "quotient.io"),
  logo("radius", "Radius", "radius.io"),
  logo("railspeed", "Railspeed", "railspeed.io"),
  logo("refractional", "Refractional", "refractional.io"),
  logo("renaissance", "Renaissance", "renaissance.io"),
  logo("screentime", "Screentime", "screentime.io"),
  logo("segment", "Segment", "segment.io"),
  logo("shutterframe", "Shutterframe", "shutterframe.io"),
  logo("sisyphus", "Sisyphus", "sisyphus.com"),
  logo("solaris-energy", "Solaris Energy", "solarise.io"),
  logo("sonorous", "Sonorous", "sonorous.io"),
  logo("spherule", "Spherule", "spherule.io"),
  logo("stack3d-lab", "Stack3d Lab", "stack3dlab.com"),
  logo("visionwork", "Visionwork", "visionwork.io"),
  logo("voxel-labs", "Voxel Labs", "voxellabs.io"),
  logo("warpspeed", "Warpspeed", "getwarpspeed.com"),
  logo("watchtower", "Watchtower", "watchtower.io"),
];

export const LOGOS_BY_SLUG = Object.fromEntries(LOGOS.map((l) => [l.slug, l]));
