import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    alert: "src/components/alert.tsx",
    badge: "src/components/badges/badge.tsx",
    "badge-with-dot": "src/components/badges/badge-with-dot.tsx",
    "badge-with-icon": "src/components/badges/badge-with-icon.tsx",
    "badge-with-flag": "src/components/badges/badge-with-flag.tsx",
    "badge-with-image": "src/components/badges/badge-with-image.tsx",
    "badge-with-button": "src/components/badges/badge-with-button.tsx",
    button: "src/components/buttons/button.tsx",
    "button-utility": "src/components/buttons/button-utility.tsx",
    "close-button": "src/components/buttons/close-button.tsx",
    "social-button": "src/components/buttons/social-button.tsx",
    "social-logos": "src/components/buttons/social-logos.tsx",
    "app-store-buttons": "src/components/buttons/app-store-buttons.tsx",
    "app-store-buttons-outline":
      "src/components/buttons/app-store-buttons-outline.tsx",
    "mac-app-store-buttons": "src/components/buttons/mac-app-store-buttons.tsx",
    card: "src/components/card.tsx",
    input: "src/components/inputs/input.tsx",
    label: "src/components/inputs/label.tsx",
    "hint-text": "src/components/inputs/hint-text.tsx",
    "input-group": "src/components/inputs/input-group.tsx",
    "input-file": "src/components/inputs/input-file.tsx",
    "input-payment": "src/components/inputs/input-payment.tsx",
    "input-date": "src/components/inputs/input-date.tsx",
    "input-number": "src/components/inputs/input-number.tsx",
    "input-tags": "src/components/inputs/input-tags.tsx",
    "pin-input": "src/components/inputs/pin-input.tsx",
    "payment-icons": "src/components/inputs/payment-icons.tsx",
    tooltip: "src/components/tooltip.tsx",
    tags: "src/components/tags.tsx",
    section: "src/components/section.tsx",
    "featured-icon": "src/components/featured-icon.tsx",
    avatar: "src/components/avatars/avatar.tsx",
    "avatar-label-group": "src/components/avatars/avatar-label-group.tsx",
    "avatar-profile-photo": "src/components/avatars/avatar-profile-photo.tsx",
    "avatar-company-icon": "src/components/avatars/avatar-company-icon.tsx",
    "avatar-count": "src/components/avatars/avatar-count.tsx",
    "avatar-add-button": "src/components/avatars/avatar-add-button.tsx",
    "progress-bar-base": "src/components/progress/progress-bar-base.tsx",
    "progress-bar": "src/components/progress/progress-bar.tsx",
    "progress-bar-circle": "src/components/progress/progress-bar-circle.tsx",
    "progress-bar-half-circle": "src/components/progress/progress-bar-half-circle.tsx",
    checkbox: "src/components/checkbox.tsx",
    radio: "src/components/radio.tsx",
    toggle: "src/components/toggle.tsx",
    textarea: "src/components/textarea.tsx",
    select: "src/components/select.tsx",
    combobox: "src/components/combobox.tsx",
    "multi-select": "src/components/multi-select.tsx",
    "tag-select": "src/components/tag-select.tsx",
    table: "src/components/table.tsx",
    "file-upload": "src/components/file-upload.tsx",
    toast: "src/components/toast.tsx",
    "command-menu": "src/components/command-menu.tsx",
    slider: "src/components/slider.tsx",
    "button-group": "src/components/buttons/button-group.tsx",
    "integration-icons": "src/components/integration-icons.tsx",
    tabs: "src/components/tabs.tsx",
    breadcrumbs: "src/components/breadcrumbs.tsx",
    pagination: "src/components/pagination.tsx",
    "empty-state": "src/components/empty-state.tsx",
    "loading-indicator": "src/components/loading-indicator.tsx",
    "badge-group": "src/components/badges/badge-group.tsx",
    "dropdown": "src/components/dropdown.tsx",
    "file-upload-trigger": "src/components/file-upload-trigger.tsx",
    "drawer": "src/components/drawer.tsx",
    "date-picker": "src/components/date-picker.tsx",
    "app-nav": "src/components/app-nav.tsx",
    "sidebar-nav": "src/components/sidebar-nav/index.tsx",
    "section-divider": "src/components/section-divider.tsx",
    "iphone-mockup": "src/components/iphone-mockup.tsx",
    "background-pattern": "src/components/background-patterns/index.tsx",
    illustration: "src/components/illustrations/index.tsx",
    "credit-card": "src/components/credit-card.tsx",
    "qr-code": "src/components/qr-code.tsx",
    form: "src/components/form.tsx",
    modal: "src/components/modal.tsx",
    "date-range-picker": "src/components/date-range-picker.tsx",
    carousel: "src/components/carousel.tsx",
    accordion: "src/components/accordion.tsx",
    sparkline: "src/components/sparkline.tsx",
    "metric-card": "src/components/metric-card.tsx",
  },
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  // Every component is a Client Component. Keep entries self-contained so the
  // `"use client"` directive can't be lost into a shared, directiveless chunk,
  // and stamp the directive onto every output file (barrel included).
  splitting: false,
  banner: { js: '"use client";' },
  external: ["react", "react-dom", "tailwindcss"],
  sourcemap: true,
});
